### PR TITLE
Update code of conduct template to CC2.0

### PR DESCRIPTION
**Pull request by CoralineAda**
### What was the end-user or developer problem that led to this PR?
The Contributor Covenant was updated to version 2.0 last year, but bundler was still using the old version.

### What is your fix for the problem, implemented in this PR?
I updated the `.md.tt` file containing the template, careful to preserve the interpolation of the email address.

### CODE REVIEW

**Comment by colby-swandale** [comment]
the CoC template needs to be added to the ignore list in the quality spec

https://github.com/rubygems/bundler/blob/13eefdc8fd166862ded7425c45270dab810003b2/spec/quality_spec.rb#L161

**Comment by colby-swandale** [comment]
Thanks! @bundlerbot r+

**Comment by colby-swandale** [comment]
@bundlerbot r+

**Comment by CoralineAda** [comment]
Thanks for the support!

**Pull request merged**
